# Generated by Django 5.0.6 on 2024-06-02 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Petend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BreadDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('bname', models.CharField(blank=True, max_length=100, null=True)),
                ('bage', models.IntegerField(blank=True, null=True)),
                ('bgender', models.CharField(blank=True, max_length=500, null=True)),
                ('bimage', models.ImageField(blank=True, null=True, upload_to='Product_images')),
            ],
        ),
    ]
