# Generated by Django 5.0.6 on 2024-07-03 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Petend', '0002_breaddb'),
    ]

    operations = [
        migrations.AddField(
            model_name='breaddb',
            name='bdescription',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='categorydb',
            name='cbread',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
