# Generated by Django 5.0.6 on 2024-07-13 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Petend', '0005_remove_categorydb_cbread'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessoriesDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aname', models.CharField(blank=True, max_length=100, null=True)),
                ('adescription', models.CharField(blank=True, max_length=500, null=True)),
                ('arate', models.IntegerField(blank=True, null=True)),
                ('aimage', models.ImageField(blank=True, null=True, upload_to='Food_images')),
            ],
        ),
        migrations.CreateModel(
            name='FoodDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(blank=True, max_length=100, null=True)),
                ('fdescription', models.CharField(blank=True, max_length=500, null=True)),
                ('frate', models.IntegerField(blank=True, null=True)),
                ('fimage', models.ImageField(blank=True, null=True, upload_to='Food_images')),
            ],
        ),
    ]
