# Generated by Django 5.0.6 on 2024-07-13 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Petend', '0006_accessoriesdb_fooddb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessoriesdb',
            name='aimage',
            field=models.ImageField(blank=True, null=True, upload_to='Accessories_images'),
        ),
    ]
