# Generated by Django 5.0.6 on 2024-07-13 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Petend', '0007_alter_accessoriesdb_aimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service1DB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('services1', models.CharField(blank=True, max_length=100, null=True)),
                ('sdescription', models.CharField(blank=True, max_length=500, null=True)),
                ('sprice', models.IntegerField(blank=True, null=True)),
                ('simage', models.ImageField(blank=True, null=True, upload_to='Service_images')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('services', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
