# Generated by Django 5.0.6 on 2024-07-13 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Petend', '0008_service1db_servicedb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service1db',
            old_name='services1',
            new_name='service1',
        ),
    ]
