# Generated by Django 5.0.6 on 2024-07-18 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Petend', '0009_rename_services1_service1db_service1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service1db',
            name='sdescription',
        ),
        migrations.AddField(
            model_name='service1db',
            name='feature1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='service1db',
            name='feature2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='service1db',
            name='feature3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='service1db',
            name='feature4',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='servicedb',
            name='sdescription',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
