# Generated by Django 5.0.6 on 2024-07-25 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Petend', '0010_remove_service1db_sdescription_service1db_feature1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='breaddb',
            name='bprice',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
