# Generated by Django 5.0.6 on 2024-07-25 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Petend', '0011_breaddb_bprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='breaddb',
            name='bvaccination',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
