# Generated by Django 5.0.6 on 2024-08-06 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Petend', '0012_breaddb_bvaccination'),
    ]

    operations = [
        migrations.AddField(
            model_name='service1db',
            name='sdescription1',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
