# Generated by Django 5.0.6 on 2024-08-14 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Petend', '0013_service1db_sdescription1'),
    ]

    operations = [
        migrations.AddField(
            model_name='breaddb',
            name='bkci',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
