# Generated by Django 5.0.6 on 2024-08-01 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0007_rename_foodname_cartdb_productname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartdb',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
