# Generated by Django 5.0.6 on 2024-08-05 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0009_orderdb'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fname', models.CharField(blank=True, max_length=100, null=True)),
                ('Fphone', models.IntegerField(blank=True, null=True)),
                ('Fsubject', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
