# Generated by Django 5.0.6 on 2024-08-05 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0010_feedbackdb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedbackdb',
            old_name='Fsubject',
            new_name='Fmessage',
        ),
    ]
