# Generated by Django 5.0.6 on 2024-08-17 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0011_rename_fsubject_feedbackdb_fmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdb',
            name='Productname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orderdb',
            name='Quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
