# Generated by Django 5.0.6 on 2024-08-17 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0012_orderdb_productname_orderdb_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdb',
            name='Productname2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
