# Generated by Django 5.0.6 on 2024-08-18 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0013_orderdb_productname2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdb',
            name='Productname2',
        ),
    ]
