# Generated by Django 5.0.6 on 2024-08-23 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0014_remove_orderdb_productname2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registerdb',
            old_name='email',
            new_name='EMAIL',
        ),
        migrations.RenameField(
            model_name='registerdb',
            old_name='password1',
            new_name='PASSWORD1',
        ),
        migrations.RenameField(
            model_name='registerdb',
            old_name='password2',
            new_name='PASSWORD2',
        ),
        migrations.RenameField(
            model_name='registerdb',
            old_name='username',
            new_name='USERNAME',
        ),
    ]
